/**
 * Rule Configurations Storage
 * This file provides localStorage-based storage for rule configurations
 * with download functionality as TypeScript file export.
 */

export interface SavedRuleConfiguration {
    ruleId: number;
    ruleName: string;
    savedAt: string;
    inputParameters: any[];
    configurationSteps: any[];
    ruleFunction: any;
}

const STORAGE_KEY = 'rce_rule_configurations';

// Get all configurations from localStorage
export const getAllRuleConfigurations = (): SavedRuleConfiguration[] => {
    try {
        const stored = localStorage.getItem(STORAGE_KEY);
        return stored ? JSON.parse(stored) : [];
    } catch (error) {
        console.error('Failed to load rule configurations from localStorage:', error);
        return [];
    }
};

// Get configuration by rule ID
export const getRuleConfiguration = (ruleId: number): SavedRuleConfiguration | undefined => {
    const configs = getAllRuleConfigurations();
    return configs.find(config => config.ruleId === ruleId);
};

// Save or update a configuration
export const saveRuleConfiguration = (config: SavedRuleConfiguration): void => {
    try {
        const configs = getAllRuleConfigurations();
        const existingIndex = configs.findIndex(c => c.ruleId === config.ruleId);

        if (existingIndex >= 0) {
            configs[existingIndex] = config;
        } else {
            configs.push(config);
        }

        localStorage.setItem(STORAGE_KEY, JSON.stringify(configs));
    } catch (error) {
        console.error('Failed to save rule configuration to localStorage:', error);
        throw error;
    }
};

// Delete a configuration
export const deleteRuleConfiguration = (ruleId: number): void => {
    try {
        const configs = getAllRuleConfigurations();
        const filtered = configs.filter(c => c.ruleId !== ruleId);
        localStorage.setItem(STORAGE_KEY, JSON.stringify(filtered));
    } catch (error) {
        console.error('Failed to delete rule configuration from localStorage:', error);
        throw error;
    }
};

// Generate TypeScript file content for download
export const generateTypeScriptExport = (config: SavedRuleConfiguration): string => {
    const sanitizedName = config.ruleName
        .replace(/[^a-zA-Z0-9]/g, '_')
        .replace(/_+/g, '_')
        .replace(/^_|_$/g, '');

    const constantName = `RULE_CONFIG_${sanitizedName.toUpperCase()}`;

    return `/**
 * Rule Configuration: ${config.ruleName}
 * Rule ID: ${config.ruleId}
 * Generated: ${config.savedAt}
 * 
 * This file was auto-generated by the Rule Configuration Engine.
 */

export interface RuleFunctionConfig {
    id: number;
    code: string;
    returnType: string;
    ruleId: number;
    inputParams: Array<{
        id: number;
        sequence: number;
        name: string;
        dataType: string;
        paramType: string;
        mandatory: string;
        default: string;
        description: string;
    }>;
    steps: Array<{
        id: string;
        type: string;
        outputVariableName: string | null;
        returnType: string;
        subFunction?: {
            id: number;
            inputParams: Array<{
                subFuncParamId: number;
                data: {
                    type: string;
                    value: string;
                };
            }>;
        };
        conditions?: any[];
        data?: {
            type: string;
            dataType: string;
            value: string;
        };
        next: string | null | { true: string | null; false: string | null };
    }>;
}

export const ${constantName}: RuleFunctionConfig = ${JSON.stringify(config.ruleFunction, null, 4)};

// Full configuration including input parameters and steps
export const ${constantName}_FULL = ${JSON.stringify(config, null, 4)};
`;
};

// Download configuration as TypeScript file
export const downloadRuleConfiguration = (config: SavedRuleConfiguration): void => {
    const tsContent = generateTypeScriptExport(config);
    const sanitizedName = config.ruleName
        .replace(/[^a-zA-Z0-9]/g, '_')
        .replace(/_+/g, '_')
        .replace(/^_|_$/g, '')
        .toLowerCase();

    const blob = new Blob([tsContent], { type: 'text/typescript' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `rule_config_${sanitizedName}.ts`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
};
